0.1 Exercises: Introduction to DataFrames
-----------------------------------------

1.  **Understanding DataFrames**\
    Create a table (DataFrame) to represent the following data:

| Student | Grade | Subject |
| --- | --- | --- |
| John | 88 | Math |
| Mary | 92 | English |
| Steve | 79 | Science |
| Linda | 85 | History |

-   Identify the **rows** and **columns**.

-   What will be the **default index**?

In [5]:
#create a list of student scores
student_scores = [
    ['Jonh', 88, 'Math'],
    ['Mary', 92, 'English'],
    ['Steve', 79, 'Science'],
    ['Linda', 85, 'History']
]

#Call the list
student_scores


#import the necessary library
import pandas as pd


#convert the list into a DataFrame
df_student_scores = pd.DataFrame(data = student_scores, columns = ['Student', 'Grade', 'Subject'])


#call the DataFrame
df_student_scores.head()

  Student  Grade  Subject
0    Jonh     88     Math
1    Mary     92  English
2   Steve     79  Science
3   Linda     85  History

In [6]:
print('The rows and columns of the DataFrame are: ')
df_student_scores.shape

The rows and columns of the DataFrame are:

(4, 3)

Default index will be 0 to 3

1.  **Custom Index**\
    Set the `Student` column as the **row index**.

    -   How does the DataFrame change?

    -   Print the DataFrame to see the new index.

In [9]:
df_student_scores_indexed = df_student_scores.set_index('Student')
df_student_scores_indexed #the student column drops to a lower level as compared to the other columns

         Grade  Subject
Student
Jonh        88     Math
Mary        92  English
Steve       79  Science
Linda       85  History

0.2 Exercises: Creating DataFrames
----------------------------------

1.  **From Dictionaries**\
    Create a DataFrame from the following dictionary:
```python
data = {

    'City': ['Nairobi', 'Mombasa', 'Kisumu'],

    'Population': [4397000, 1200000, 409000],

    'Country': ['Kenya', 'Kenya', 'Kenya']

}
```
-   Print the first 2 rows using `.head()`.

-   Print the DataFrame info using `.info()`

In [11]:
data = {

    'City': ['Nairobi', 'Mombasa', 'Kisumu'],

    'Population': [4397000, 1200000, 409000],

    'Country': ['Kenya', 'Kenya', 'Kenya']

}

kenyan_cities_dict = data

df_kenyan_cities_dict = pd.DataFrame(data = kenyan_cities_dict)

#Print the first 2 rows using `.head()`
df_kenyan_cities_dict.head(2)

      City  Population Country
0  Nairobi     4397000   Kenya
1  Mombasa     1200000   Kenya

In [12]:
#Print the DataFrame info using `.info()`

df_kenyan_cities_dict.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        3 non-null      str
 1   Population  3 non-null      int64
 2   Country     3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

1.  **From Lists**\
    Create a DataFrame from this list of lists:
```python
data = [

    ['Apple', 120, 0.5],

    ['Banana', 80, 0.2],

    ['Cherry', 200, 1.5]

]
```
-   Set column names to `['Fruit', 'Quantity', 'Price']`.

-   Print the shape and column data types.

In [14]:
data = [

    ['Apple', 120, 0.5],

    ['Banana', 80, 0.2],

    ['Cherry', 200, 1.5]

]

fruits_shopping_list = data

fruits_shopping_df = pd.DataFrame(data = fruits_shopping_list, columns = ['Fruit', 'Quantity', 'Price'])
fruits_shopping_df.shape

(3, 3)

In [83]:
#Print the column data types.

fruits_shopping_df.dtypes

Fruit           str
Quantity      int64
Price       float64
dtype: object

1.  **Inspecting DataFrames**\
    Using any DataFrame you created above, perform the following:

-   Show the first 3 rows.

-   Show the last 2 rows.

In [16]:
#Show the first 3 rows.

fruits_shopping_df.head(3)

    Fruit  Quantity  Price
0   Apple       120    0.5
1  Banana        80    0.2
2  Cherry       200    1.5

In [17]:
#Show the last 2 rows

fruits_shopping_df.tail(2)

    Fruit  Quantity  Price
1  Banana        80    0.2
2  Cherry       200    1.5

0.3 Exercises: Selecting and Filtering Data
-------------------------------------------

1.  **Column Selection**\
    Using the fruit DataFrame from the previous exercise:

-   Select only the `Fruit` column.

-   Select `Fruit` and `Price` columns.

In [21]:
#Select only the `Fruit` column

fruits_shopping_df['Fruit']

0     Apple
1    Banana
2    Cherry
Name: Fruit, dtype: str

In [33]:
 #Select `Fruit` and `Price` columns.

fruits_shopping_df[['Fruit', 'Price']]

    Fruit  Price
0   Apple    0.5
1  Banana    0.2
2  Cherry    1.5

1.  **Row Selection**\
    Using `.loc` and `.iloc`:

-   Select the second row using `.iloc`.

-   Select the row where `Fruit` is `'Cherry'` using `.loc`.

-   Select the first two rows and the `Fruit` and `Quantity` columns.

In [86]:
fruits_shopping_df

    Fruit  Quantity  Price
0   Apple       120    0.5
1  Banana        80    0.2
2  Cherry       200    1.5

In [105]:
#Select the second row using `.iloc`.

fruits_shopping_df.iloc[[1]] #double brackets to return a row and not a serries

    Fruit  Quantity  Price
1  Banana        80    0.2

In [101]:
#Select the second row using `.iloc`.

fruits_shopping_df.iloc[1] #returns a series not a row

Fruit       Banana
Quantity        80
Price          0.2
Name: 1, dtype: object

In [106]:
#Select the row where `Fruit` is `'Cherry'` using `.loc`.
fruits_shopping_df.loc[[2]]

    Fruit  Quantity  Price
2  Cherry       200    1.5

In [107]:
#Select the first two rows and the `Fruit` and `Quantity` columns.

fruits_shopping_df

fruits_shopping_df[['Fruit', 'Quantity']].iloc[0:2]

    Fruit  Quantity
0   Apple       120
1  Banana        80

1.  **Boolean Filtering**

-   Select all fruits with `Quantity > 100`.

-   Select all fruits with `Price > 0.5` **AND** `Quantity < 150`.

-   Select all fruits with `Price < 1` **OR** `Quantity > 150`.

In [45]:
#Select all fruits with `Quantity > 100`

fruits_shopping_df[fruits_shopping_df['Quantity'] > 100]

    Fruit  Quantity  Price
0   Apple       120    0.5
2  Cherry       200    1.5

In [67]:
#Select all fruits with `Price > 0.5` **AND** `Quantity < 150`.

fruits_shopping_df[(fruits_shopping_df['Price'] > 0.5) & (fruits_shopping_df['Quantity'] < 150)]

Empty DataFrame
Columns: [Fruit, Quantity, Price]
Index: []

In [65]:
fruits_shopping_df

    Fruit  Quantity  Price
0   Apple       120    0.5
1  Banana        80    0.2
2  Cherry       200    1.5

In [70]:
#Select all fruits with `Price < 1` **OR** `Quantity > 150`.

fruits_shopping_df[(fruits_shopping_df['Price'] < 1) | (fruits_shopping_df['Quantity'] > 150)]

    Fruit  Quantity  Price
0   Apple       120    0.5
1  Banana        80    0.2
2  Cherry       200    1.5

1.  **Copy vs View**

-   Create a subset of the fruit DataFrame with only `Fruit` and `Price` columns using `.copy()`.

-   Increase the `Price` by 10% in the subset.

-   Verify that the original DataFrame is **not affected**.

In [79]:
subset_df = fruits_shopping_df[['Fruit', 'Price']].copy()

subset_df

    Fruit  Price
0   Apple    0.5
1  Banana    0.2
2  Cherry    1.5

In [80]:
#increasing the price in the subset by 10% will be current price = 100%, new price after increase
#will be 100% + 10% , thus 110% which is 110% change into decimals = 1.1


subset_df['Price'] *= 1.1
subset_df

    Fruit  Price
0   Apple   0.55
1  Banana   0.22
2  Cherry   1.65

In [81]:
#calling the original df to show that it wasn't affected by 10% price increase done on the copy
fruits_shopping_df

    Fruit  Quantity  Price
0   Apple       120    0.5
1  Banana        80    0.2
2  Cherry       200    1.5