Chapter 3 Practice Exercises: Data Cleaning
===========================================

These exercises will help you practice cleaning messy data so it is ready for analysis. Try solving them on your own before checking solutions.
3.1 Exercises: String Columns

1.Converting and Trimming Strings
    
    Assume a column Name has inconsistent data: " Alice ", "BOB", "Charlie " 
    Convert all names to string type.
    Remove extra spaces using .str.strip().
    Convert all names to title case.

In [36]:
import pandas as pd

data_names = ['Alice', 'BOB', 'Charlie'] #creating names as a list 

names_df = pd.DataFrame(data = data_names, columns = ['Name']) #creating a DataFrame with name column
names_df.head()

      Name
0    Alice
1      BOB
2  Charlie

In [37]:
#cleaning the name column in the created df
names_df['Name_clean'] = names_df['Name'].str.strip().str.title()
names_df

      Name Name_clean
0    Alice      Alice
1      BOB        Bob
2  Charlie    Charlie

In [38]:
#to confirm no whitespaces and the code was successful i will use .apply(repr) it shows whitespaces, tab, indent
#For title case i can confirm with my visible but i can also use (.istitle()) just to confirm. for data type 
#i could use .dtype

names_df['Name_clean'].apply(repr) #this checks for whitespaces

0      'Alice'
1        'Bob'
2    'Charlie'
Name: Name_clean, dtype: str

In [39]:
names_df['Name_clean'].dtype #confirms that our name column is in string format

2. Replacing Characters and Removing Special Characters

    Column Code contains values: "A-123", "B_456", "C@789!"
    Replace "-" with "_".
    Remove special characters like @ and ! using regex.

In [40]:
codes =['A-123', 'B_456', 'C@789!']
             
names_df['Id_codes'] = codes

names_df.head()

      Name Name_clean Id_codes
0    Alice      Alice    A-123
1      BOB        Bob    B_456
2  Charlie    Charlie   C@789!

In [41]:
# Replace "-" with "_".
# method 1

names_df['Id_codes_cleaned'] = names_df['Id_codes'].str.replace('-', '_', regex = True).str.replace('@', '_', regex = True).str.replace('!', '', regex = True)

names_df[['Id_codes_cleaned', 'Id_codes']]

  Id_codes_cleaned Id_codes
0            A_123    A-123
1            B_456    B_456
2            C_789   C@789!

In [42]:
#Remove special characters like @ and ! using regex.
#method 2
names_df['Id_codes'].str.strip().replace('-', '_', regex = True).str.replace(r'(\W)', '', regex = True) 

#'(\W)' replaces non-word characters, that is @ and !

0    A_123
1    B_456
2     C789
Name: Id_codes, dtype: str

3. Standardizing Categorical Values

    Column Gender has values: "M", "F", "male", "Female"
    Standardize all values to "male" and "female".

In [46]:
#Column Gender has values: "M", "F", "male", "Female"

genders = ['M', 'F', 'male', 'female']

names_df = names_df.reindex(range(len(genders))) #reindex fixes names_df to accomodate the 
#fourth row brought about by genders
names_df['Gender'] = genders
names_df.head()

      Name Name_clean Id_codes Id_codes_cleaned  Gender
0    Alice      Alice    A-123            A_123       M
1      BOB        Bob    B_456            B_456       F
2  Charlie    Charlie   C@789!            C_789    male
3      NaN        NaN      NaN              NaN  female

In [50]:
#Standardize all values to "male" and "female"

names_df['Gender_clean'] = names_df['Gender'].str.lower().replace({'m':'male', 'f':'female'}) #I used a dictionary because i was replacing
#more than one value that is 'M' and 'F'

names_df[['Gender', 'Gender_clean']]

   Gender Gender_clean
0       M         male
1       F       female
2    male         male
3  female       female

4. Extracting Text and Checking Length

    Column ProductCode has values: "AB1234", "CD5678", "EF9012"
    Extract the numeric part using .str.extract().
    Check the length of each string in ProductCode

In [53]:
productcode = ["AB1234", "CD5678", "EF9012", None] # i will include None because 
#names_df was expanded by Gender column

names_df['Product_code'] = productcode
names_df.head()

,Name,Name_clean,Id_codes,Id_codes_cleaned,Gender,Gender_clean,Product_code
0,Alice,Alice,A-123,A_123,M,male,AB1234
1,BOB,Bob,B_456,B_456,F,female,CD5678
2,Charlie,Charlie,C@789!,C_789,male,male,EF9012
3,NaN,NaN,NaN,NaN,female,female,NaN

In [56]:
 #Extract the numeric part using .str.extract().

names_df['Product_code_clean'] = names_df['Product_code'].str.extract(r'(\d+)') 

# '\d' extracts digits 
#the '+' means we are extracting more than one digit

names_df[['Product_code', 'Product_code_clean']]

  Product_code Product_code_clean
0       AB1234               1234
1       CD5678               5678
2       EF9012               9012
3          NaN                NaN

In [59]:
#Check the length of each string in ProductCode
names_df['Product_code_clean'].str.len()

0    4.0
1    4.0
2    4.0
3    NaN
Name: Product_code_clean, dtype: float64

3.2 Exercises: Numeric Columns

1.Converting to Numeric and Handling Errors

    Column Age contains: 25, "30", "unknown", 40
    Convert the column to numeric using pd.to_numeric() with errors='coerce'.
    Identify the resulting missing value.

In [57]:
age = [25, "30", "unknown", 40]

names_df['Age'] = age
names_df.info() #by using .info() we can see that Age has been created as an object
#that is we don't know whether its str, float, int

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                3 non-null      str
 1   Name_clean          3 non-null      str
 2   Id_codes            3 non-null      str
 3   Id_codes_cleaned    3 non-null      str
 4   Gender              4 non-null      str
 5   Gender_clean        4 non-null      str
 6   Product_code        3 non-null      str
 7   Product_code_clean  3 non-null      str
 8   Age                 4 non-null      object
dtypes: object(1), str(8)
memory usage: 420.0+ bytes

In [62]:
#Convert the column to numeric using pd.to_numeric() with errors='coerce'.

names_df['Age_clean'] = pd.to_numeric(names_df['Age'], errors = 'coerce')

names_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                3 non-null      str
 1   Name_clean          3 non-null      str
 2   Id_codes            3 non-null      str
 3   Id_codes_cleaned    3 non-null      str
 4   Gender              4 non-null      str
 5   Gender_clean        4 non-null      str
 6   Product_code        3 non-null      str
 7   Product_code_clean  3 non-null      str
 8   Age                 4 non-null      object
 9   Age_clean           3 non-null      float64
dtypes: float64(1), object(1), str(8)
memory usage: 452.0+ bytes

In [66]:
#Identify the resulting missing value.

names_df['Age_clean'].isna()

0    False
1    False
2     True
3    False
Name: Age_clean, dtype: bool

In [67]:
names_df[names_df['Age_clean'].isna()] #deep diving to check which row has missing value

,Name,Name_clean,Id_codes,Id_codes_cleaned,Gender,Gender_clean,Product_code,Product_code_clean,Age,Age_clean
2,Charlie,Charlie,C@789!,C_789,male,male,EF9012,9012,unknown,NaN

In [71]:
names_df['Age_clean'].unique() #this is also can help us identify the missing value

array([25., 30., nan, 40.])

2. Rounding and Replacing Values

    Column Price contains: 1.234, 2.567, 3.891
    Round all prices to 2 decimal places.
    Replace any negative values with 0

In [72]:
price = [1.234, 2.567, 3.891, -2.375]

names_df['Price'] = price

names_df.head()

,Name,Name_clean,Id_codes,Id_codes_cleaned,Gender,Gender_clean,Product_code,Product_code_clean,Age,Age_clean,Price
0,Alice,Alice,A-123,A_123,M,male,AB1234,1234,25,25.0,1.234
1,BOB,Bob,B_456,B_456,F,female,CD5678,5678,30,30.0,2.567
2,Charlie,Charlie,C@789!,C_789,male,male,EF9012,9012,unknown,NaN,3.891
3,NaN,NaN,NaN,NaN,female,female,NaN,NaN,40,40.0,-2.375

In [86]:
#Round all prices to 2 decimal places.

names_df['Price_clean'] = names_df['Price'].round(2)

names_df[['Price', 'Price_clean']]

   Price  Price_clean
0  1.234         1.23
1  2.567         2.57
2  3.891         3.89
3 -2.375        -2.38

In [87]:
#Replace any negative values with absolute

names_df['Price_clean'].abs() 

#in this case using absolute would be the best solution
#since there can never be a negative price unless it was meant to indicate the product was bought at a debt
#or was a loss or it could be an obvious typo!

0    1.23
1    2.57
2    3.89
3    2.38
Name: Price_clean, dtype: float64

In [88]:
#Replace any negative values with 0
#method 1 using .clip(lower=0)

names_df['Price_clean'].clip(lower = 0)

0    1.23
1    2.57
2    3.89
3    0.00
Name: Price_clean, dtype: float64

In [89]:
#Replace any negative values with 0

#method 2 using '.loc()'

names_df.loc[names_df['Price_clean'] < 0, 'Price_clean'] = 0

names_df[['Price', 'Price_clean']]

   Price  Price_clean
0  1.234         1.23
1  2.567         2.57
2  3.891         3.89
3 -2.375         0.00

3. Filling Missing Values

   Column Score has missing values (NaN).
    Fill missing values with mean, median, or a constant of your choice.

3.3 Exercises: Date Columns

1.Converting to Datetime

    Column JoinDate contains: "2023-01-15", "15/02/2023", "March 5, 2023"
    Convert the column to datetime, handling mixed formats.

2. Handling Invalid Dates and Missing Values

    Add a value "2023-15-01" (invalid date) and NaN.
    Convert to datetime using errors='coerce'.
    Fill missing or invalid dates with a default value "2000-01-01"

3. Extracting Date Parts

    Extract year, month, and day into separate columns for validation.

3.4 Exercises: Table-Level Cleaning

1.Removing Duplicates and Missing Values

    Create a DataFrame with duplicate rows and missing values.
    Remove duplicates using .drop_duplicates().
    Drop rows with missing values in a specific column using .dropna(subset=[...]).

2. Renaming and Standardizing Column Names

Columns: "First Name", "Last Name", "Join Date"
Rename columns to snake_case using .str.lower(), .str.strip(), and .str.replace(' ', '_').

3. Resetting and Setting Index

Set the ID column as the new index.
Reset the index back to default numeric index.